"""create forecasts table

Revision ID: 0aafac9bc5dc
Revises: 
Create Date: 2026-07-20 11:45:13.086700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aafac9bc5dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('forecast_time', sa.DateTime(), nullable=False),
    sa.Column('predicted_power_kw', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_asset_id'), 'forecasts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_time'), 'forecasts', ['forecast_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_forecast_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_asset_id'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
