"""added forecast requirements models and based_on_revision fields

Revision ID: 3a57b6662e91
Revises: 657bc7a46884
Create Date: 2026-09-08 08:02:09.672439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a57b6662e91'
down_revision: Union[str, Sequence[str], None] = '657bc7a46884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_forecast_requirements',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('required_revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('portfolio_forecast_requirements',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('required_revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.add_column('asset_forecasts', sa.Column('based_on_revision', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE asset_forecasts SET based_on_revision = 0 WHERE based_on_revision IS NULL"
    )

    op.alter_column(
        "asset_forecasts",
        "based_on_revision",
        nullable=False,
    )
    op.add_column('portfolio_forecasts', sa.Column('based_on_revision', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE portfolio_forecasts SET based_on_revision = 0 WHERE based_on_revision IS NULL"
    )

    op.alter_column(
        "portfolio_forecasts",
        "based_on_revision",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_forecasts', 'based_on_revision')
    op.drop_column('asset_forecasts', 'based_on_revision')
    op.drop_table('portfolio_forecast_requirements')
    op.drop_table('asset_forecast_requirements')
    # ### end Alembic commands ###
