"""adding based_on_weather_forecast_id field to asset_forecast

Revision ID: 844945f633ca
Revises: 3a57b6662e91
Create Date: 2026-09-09 09:14:51.804893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844945f633ca'
down_revision: Union[str, Sequence[str], None] = '3a57b6662e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_forecasts', sa.Column('based_on_weather_forecast_id', sa.Integer(), nullable=True))

    # naive default value to let prevent migration from failing
    op.execute(
        "UPDATE asset_forecasts SET based_on_weather_forecast_id = (SELECT id from weather_forecasts LIMIT 1) WHERE based_on_weather_forecast_id IS NULL"
    )
    op.create_foreign_key(None, 'asset_forecasts', 'weather_forecasts', ['based_on_weather_forecast_id'], ['id'])

    op.alter_column(
        "asset_forecasts",
        "based_on_weather_forecast_id",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_forecasts', type_='foreignkey')
    op.drop_column('asset_forecasts', 'based_on_weather_forecast_id')
    # ### end Alembic commands ###
