"""creating new forecast tables

Revision ID: ac14b7161353
Revises: 9359d7e38626
Create Date: 2026-07-27 11:30:39.484103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac14b7161353'
down_revision: Union[str, Sequence[str], None] = '0aafac9bc5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_start', sa.DateTime(), nullable=False),
    sa.Column('horizon_end', sa.DateTime(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('prediction_p05', sa.Float(), nullable=False),
    sa.Column('prediction_p50', sa.Float(), nullable=False),
    sa.Column('prediction_p95', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('prediction_p05', sa.Float(), nullable=False),
    sa.Column('prediction_p50', sa.Float(), nullable=False),
    sa.Column('prediction_p95', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weather_forecast_run_id'], ['weather_forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(length=50), nullable=False),
    sa.Column('p05', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p95', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['weather_forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_forecasts_asset_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_time'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forecast_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('predicted_power_kw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('forecasts_pkey'))
    )
    op.create_index(op.f('ix_forecasts_forecast_time'), 'forecasts', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_forecasts_asset_id'), 'forecasts', ['asset_id'], unique=False)
    op.drop_table('weather_variables')
    op.drop_table('weather_forecasts')
    op.drop_table('portfolio_forecasts')
    op.drop_table('asset_forecasts')
    op.drop_table('weather_forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
