apiVersion: 1
datasources:
  - id: 2
    uid: "ag0pm7enqq4n4a"
    orgId: 1
    name: "yesoreyeram-infinity-datasource"
    type: "yesoreyeram-infinity-datasource"
    url: "http://dependency-analyzer:8000/api/"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      global_queries: []
      pdcInjected: false
    readOnly: false
    apiVersion: ""