services:

  test-exporter:
    build:
      context: ./test-exporter
    container_name: test-exporter
    volumes:
      - ./test-exporter/app:/app/app
      - ../test-artifacts:/test-artifacts:ro
    networks:
      - observability
  prometheus:
    image: prom/prometheus:latest
    container_name: project-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - observability
    depends_on:
      - test-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: project-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - observability
    environment:
      GF_PLUGINS_PREINSTALL: "grafana-graphviz-panel,yesoreyeram-infinity-datasource"

  dependency-analyzer:
    build:
      context: ./dependency-analyzer
    volumes:
      - ../services/asset-service:/projects/asset-service:ro
      - ../services/forecast-service:/projects/forecast-service:ro
      - ./dependency-artifacts:/artifacts
    restart: unless-stopped
    networks:
      - observability

volumes:
  prometheus-data:
  grafana-data:

networks:
  observability: