"""add asset configurations

Revision ID: a0eac7646d4d
Revises: 823816111846
Create Date: 2026-08-04 18:34:48.542724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eac7646d4d'
down_revision: Union[str, Sequence[str], None] = '823816111846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_asset_configurations',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('max_charge_kw', sa.Float(), nullable=False),
    sa.Column('max_discharge_kw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('pv_asset_configurations',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('panel_area_m2', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('tilt_deg', sa.Float(), nullable=False),
    sa.Column('azimuth_deg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('wind_asset_configurations',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('hub_height_m', sa.Float(), nullable=False),
    sa.Column('rotor_diameter_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_asset_configurations')
    op.drop_table('pv_asset_configurations')
    op.drop_table('battery_asset_configurations')
    # ### end Alembic commands ###
