"""added asset and portfolio revision

Revision ID: c0540da77aa6
Revises: a0eac7646d4d
Create Date: 2026-09-08 07:23:02.664955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0540da77aa6'
down_revision: Union[str, Sequence[str], None] = 'a0eac7646d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('revision', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE assets SET revision = 0 WHERE revision IS NULL"
    )

    op.alter_column(
        "assets",
        "revision",
        nullable=False,
    )
    op.add_column('portfolios', sa.Column('revision', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE portfolios SET revision = 0 WHERE revision IS NULL"
    )

    op.alter_column(
        "portfolios",
        "revision",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'revision')
    op.drop_column('assets', 'revision')
    # ### end Alembic commands ###
